services:
  worker:
    image: ${WORKER_IMAGE_URI}
    deploy:
      restart_policy:
        max_attempts: 3
        condition: on-failure
        delay: 10s
    environment:
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - HLS2TLGRUPLOADER__TELEGRAM__APIURL=http://telegram-bot-api-server:8081
    depends_on:
      - telegram-bot-api-server
    tmpfs:
      - /tmp/bounan-downloader:mode=777
  
  telegram-bot-api-server:
    image: aiogram/telegram-bot-api:8.3
    deploy:
      restart_policy:
        max_attempts: 3
        condition: on-failure
        delay: 10s
    environment:
      - TELEGRAM_LOCAL
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
