services:
  worker:
    build:
      context: .
      dockerfile: src/Worker/Dockerfile
    deploy:
      restart_policy:
        max_attempts: 3
        condition: on-failure
        delay: 10s
    environment:
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - LoanApi__Token=${LoanApi__Token}
      - Logging__LogGroup=${Logging__LogGroup}
      - Telegram__ApiUrl=http://telegram-bot-api-server:8081
      - Telegram__BotToken=${Telegram__BotToken}
      - Telegram__DestinationChatId=${Telegram__DestinationChatId}
      - AniMan__GetVideoToDownloadLambdaFunctionName=${AniMan__GetVideoToDownloadLambdaFunctionName}
      - AniMan__UpdateVideoStatusLambdaFunctionName=${AniMan__UpdateVideoStatusLambdaFunctionName}
      - Sqs__NotificationQueueUrl=${Sqs__NotificationQueueUrl}
      - Processing__Threads=${Processing__Threads}
      - Thumbnail__BotId=${Thumbnail__BotId}
      - VideoService__TimeoutSeconds=${VideoService__TimeoutSeconds}
    links:
      - telegram-bot-api-server
  
  telegram-bot-api-server:
    image: aiogram/telegram-bot-api:7.1
    deploy:
      restart_policy:
        max_attempts: 3
        condition: on-failure
        delay: 10s
    environment:
      - TELEGRAM_LOCAL
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
